local M = {}

-- icons collection
M.icon_sets = {
  --   
  diagnostic_states = {
    outline  = { Error = "", Warn = "", Hint = "", Info = "" },
    full     = { Error = "", Warn = "", Hint = "", Info = "" },
    cozette  = { Error = "", Warn = "", Hint = "", Info = "" },
    codicons = { Error = "", Warn = "", Hint = "", Info = "" },
    letters  = { Error = "E", Warn = "W", Hint = "H", Info = "I" },
    none     = { Error = " ", Warn = " ", Hint = " ", Info = " " },
  },
  item_kinds = {
    -- ⌂ θ ғ  Ω
    cozette = {
      Text          = '',
      Method        = '',
      Function      = '',
      Constructor   = '',
      Field         = 'ﴲ',
      Variable      = '',
      Class         = '',
      Interface     = 'ﰮ',
      Module        = '',
      Property      = '',
      Unit          = '',
      Value         = '',
      Enum          = '',
      Keyword       = '',
      Snippet       = '',
      Color         = '',
      File          = '',
      Reference     = '',
      Folder        = '',
      EnumMember    = '',
      Constant      = '',
      Struct        = 'ﳤ',
      Event         = '',
      Operator      = '',
      TypeParameter = '',

      Namespace = '',
      Package   = '',
      String    = '',
      Number    = '',
      Boolean   = '✓',
      Array     = '',
      Object    = '',
      Key       = '',
      Null      = '⌀',
    },
    codicons = {
      Text          = '',
      Method        = '',
      Function      = '',
      Constructor   = '',
      Field         = '',
      Variable      = '',
      Class         = '',
      Interface     = '',
      Module        = '',
      Property      = '',
      Unit          = '',
      Value         = '',
      Enum          = '',
      Keyword       = '',
      Snippet       = '',
      Color         = '',
      File          = '',
      Reference     = '',
      Folder        = '',
      EnumMember    = '',
      Constant      = '',
      Struct        = '',
      Event         = '',
      Operator      = '',
      TypeParameter = '',

      Namespace = '',
      Package   = '',
      String    = '',
      Number    = '',
      Boolean   = '',
      Array     = '',
      Object    = '',
      Key       = '',
      Null      = '',
    },
    nerdfont = {
      Text          = '',
      Method        = '',
      Function      = '',
      Constructor   = '',
      Field         = 'ﴲ',
      Variable      = '',
      Class         = '',
      Interface     = 'ﰮ',
      Module        = '',
      Property      = '襁',
      Unit          = '',
      Value         = '',
      Enum          = '',
      Keyword       = '',
      Snippet       = '',
      Color         = '',
      File          = '',
      Reference     = '',
      Folder        = '',
      EnumMember    = '',
      Constant      = '',
      Struct        = 'ﳤ',
      Event         = '',
      Operator      = '',
      TypeParameter = '',

      Namespace = '',
      Package   = '',
      String    = '',
      Number    = '',
      Boolean   = '◩',
      Array     = '',
      Object    = '',
      Key       = '',
      Null      = 'ﳠ',
    },
  },
  ui = {
    codicons = {
      breakpoint = '',
      expanded = '',
      collapsed = '',
    }
  },
}

return M
