local M = {
  plenary                     = { url = "nvim-lua/plenary.nvim" },
  mason                       = { url = "williamboman/mason.nvim" },
  lspconfig                   = { url = "neovim/nvim-lspconfig" },
  mason_lspconfig             = { url = "williamboman/mason-lspconfig.nvim" },
  typescript_tools            = { url = "pmizio/typescript-tools.nvim" },
  lazydev                     = { url = "folke/lazydev.nvim" },
  luvit_meta                  = { url = "Bilal2453/luvit-meta" },
  mini                        = { url = "echasnovski/mini.nvim" },
  treesitter                  = { url = "nvim-treesitter/nvim-treesitter" },
  treesitter_comments         = { url = "folke/ts-comments.nvim" },
  neotree                     = { url = "nvim-neo-tree/neo-tree.nvim" },
  fold_cycle                  = { url = "jghauser/fold-cycle.nvim" },
  codeium                     = { url = "Exafunction/codeium.nvim" },
  copilot                     = { url = "zbirenbaum/copilot.lua" },
  autocomplete                = { url = "deathbeam/autocomplete.nvim" },
  cmp                         = { url = "hrsh7th/nvim-cmp" },
  -- cmp_nvim_lsp_signature_help = { url = "hrsh7th/cmp-nvim-lsp-signature-help" },
  -- cmp_rg                      = { url = "lukas-reineke/cmp-rg" },
  cmp_path                    = { url = "hrsh7th/cmp-path" },
  cmp_nvim_lsp                = { url = "hrsh7th/cmp-nvim-lsp" },
  cmp_nvim_lua                = { url = "hrsh7th/cmp-nvim-lua" },
  -- cmp_luasnip                 = { url = "saadparwaiz1/cmp_luasnip" },
  cmp_cmdline                 = { url = "hrsh7th/cmp-cmdline" },
  cmp_buffer                  = { url = "hrsh7th/cmp-buffer" },
  -- sfm                         = { url = "dinhhuy258/sfm.nvim" },
  -- sfm_git                     = { url = "dinhhuy258/sfm-git.nvim" },
  devicons                    = { url = "nvim-tree/nvim-web-devicons" },
  heirline                    = { url = "rebelot/heirline.nvim" },
  gitsigns                    = { url = "lewis6991/gitsigns.nvim" },
  git_conflict                = { url = "akinsho/git-conflict.nvim" },
  dressing                    = { url = "stevearc/dressing.nvim" },
  corn                        = { url = "RaafatTurki/corn.nvim" },
  hex                         = { url = "RaafatTurki/hex.nvim" },
  view                        = { url = "RaafatTurki/view.nvim" },
  lightbulb                   = { url = "kosayoda/nvim-lightbulb" },
  omnisharp_ext               = { url = "Hoffs/omnisharp-extended-lsp.nvim" },
  hurl                        = { url = "jellydn/hurl.nvim" },
  nui                         = { url = "MunifTanjim/nui.nvim" },
  highlight_colors            = { url = "brenoprata10/nvim-highlight-colors" },
  zen_mode                    = { url = "folke/zen-mode.nvim" },
  -- blame                       = { url = "FabijanZulj/blame.nvim" },
  -- diffview                    = { url = "sindrets/diffview.nvim" },
  -- image                       = { url = "3rd/image.nvim" },
  -- img_clip                    = { url = "hakonharnes/img-clip.nvim" },
  -- fidget                      = { url = "j-hui/fidget.nvim" },
  -- noice                       = { url = "folke/noice.nvim" },
  -- lsp_overloads               = { url = "Issafalcon/lsp-overloads.nvim" },
  -- dial                        = { url = "monaqa/dial.nvim" },
  -- nvim_bqf                    = { url = "kevinhwang91/nvim-bqf" },
}

return M
