local M = {
  plenary                     = { url = "nvim-lua/plenary.nvim" },
  mason                       = { url = "williamboman/mason.nvim" },
  lspconfig                   = { url = "neovim/nvim-lspconfig" },
  mason_lspconfig             = { url = "williamboman/mason-lspconfig.nvim" },
  neodev                      = { url = "folke/neodev.nvim" },
  mini                        = { url = "echasnovski/mini.nvim", },
  treesitter                  = { url = "nvim-treesitter/nvim-treesitter" },
  treesitter_ctx_cms          = { url = "JoosepAlviste/nvim-ts-context-commentstring" },
  -- treesitter_ctx              = { url = "nvim-treesitter/nvim-treesitter-context" },
  fold_cycle                  = { url = "jghauser/fold-cycle.nvim" },
  luasnip                     = { url = "L3MON4D3/LuaSnip" },
  copilot                     = { url = "zbirenbaum/copilot.lua" },
  cmp                         = { url = "hrsh7th/nvim-cmp" },
  -- cmp_nvim_lsp_signature_help = { url = "hrsh7th/cmp-nvim-lsp-signature-help" },
  -- cmp_rg                      = { url = "lukas-reineke/cmp-rg" },
  cmp_path                    = { url = "hrsh7th/cmp-path" },
  cmp_nvim_lsp                = { url = "hrsh7th/cmp-nvim-lsp" },
  cmp_nvim_lua                = { url = "hrsh7th/cmp-nvim-lua" },
  cmp_luasnip                 = { url = "saadparwaiz1/cmp_luasnip" },
  cmp_cmdline                 = { url = "hrsh7th/cmp-cmdline" },
  cmp_buffer                  = { url = "hrsh7th/cmp-buffer" },
  sfm                         = { url = "dinhhuy258/sfm.nvim" },
  sfm_git                     = { url = "dinhhuy258/sfm-git.nvim" },
  devicons                    = { url = "nvim-tree/nvim-web-devicons" },
  -- telescope                   = { url = "nvim-telescope/telescope.nvim" },
  -- telescope_fzf               = { url = "nvim-telescope/telescope-fzf-native.nvim" },
  -- statuscol                   = { url = "luukvbaal/statuscol.nvim" },
  heirline                    = { url = "rebelot/heirline.nvim" },
  gitsigns                    = { url = "lewis6991/gitsigns.nvim" },
  git_conflict                = { url = "akinsho/git-conflict.nvim" },
  dressing                    = { url = "stevearc/dressing.nvim" },
  corn                        = { url = "RaafatTurki/corn.nvim" },
  -- lsp_signature               = { url = "ray-x/lsp_signature.nvim" },
  lightbulb                   = { url = "kosayoda/nvim-lightbulb" },
  omnisharp_ext               = { url = "Hoffs/omnisharp-extended-lsp.nvim" },
  typst_vim                   = { url = "kaarmu/typst.vim" },
  -- image                       = { url = "3rd/image.nvim" },
  -- img_clip                    = { url = "hakonharnes/img-clip.nvim" },
  -- fidget                      = { url = "j-hui/fidget.nvim" },
  -- flutter                     = { url = "akinsho/flutter-tools.nvim" },
  -- typst                       = { url = "kaarmu/typst.vim" },
  -- noice                       = { url = "folke/noice.nvim" },
  -- lsp_overloads               = { url = "Issafalcon/lsp-overloads.nvim" },
  -- dial                        = { url = "monaqa/dial.nvim" },
  -- nvim_bqf                    = { url = "kevinhwang91/nvim-bqf" },
}

return M
