-- local avante = require "avante"

-- TODO: make this happen only once on install automatically
-- # BUILD STEP
-- if vim.fn.has 'win32' == 1 then
--   return 'powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false'
-- else
--   return 'make'
-- end

-- avante.setup {
--   provider = "codex",
--   acp_providers = {
--     ["codex"] = {
--       command = "npx",
--       args = { "@zed-industries/codex-acp" },
--       env = {
--         NODE_NO_WARNINGS = "1",
--         OPENAI_API_KEY = os.getenv("OPENAI_API_KEY"),
--       },
--     },
--   },
--
--   -- system_prompt as function ensures LLM always has latest MCP server state This is evaluated for every message, even in existing chats
--   system_prompt = function()
--     local hub = require('mcphub').get_hub_instance()
--     return hub and hub:get_active_servers_prompt() or ''
--   end,
--
--   -- using function prevents requiring mcphub before it's loaded
--   custom_tools = function()
--     return {
--       require('mcphub.extensions.avante').mcp_tool(),
--     }
--   end,
-- }

--   ---@module 'avante'
--   
--   opts = {
--     -- add any opts here
--     -- for example
--     provider = 'claude',
--     -- provider = 'openai',
--     providers = {
--       claude = {
--       -- openai = {
--         endpoint = '<https://api.anthropic.com>',
--         model = "claude-sonnet-4-20250514",
--         api_key_name = 'CLAUDE_API_KEY',
--         -- model = 'o3-mini',
--         -- api_key_name = 'OPENAI_API_KEY',
--         timeout = 30000, -- Timeout in milliseconds
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 20480,
--         },
--       },
--     },
--   },

--   dependencies = {
--     'ibhagwan/fzf-lua', -- for file_selector provider fzf
--     'stevearc/dressing.nvim', -- for input provider dressing
--     'folke/snacks.nvim', -- for input provider snacks
--     'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
--     'zbirenbaum/copilot.lua', -- for providers='copilot'

--     {
--       -- Make sure to set this up properly if you have lazy=true
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { 'markdown', 'Avante' },
--       },
--       ft = { 'markdown', 'Avante' },
--     },
--   },
