-- TODO: make this happen only once on install automatically
-- # BUILD STEP
-- vim.system({ "bun", "install", "-g", "mcp-hub@latest" }, { text = true, timeout = 30000 }, function(result)
--   if result.code ~= 0 then
--     vim.notify("mcphub build step failed with code " .. result.code .. ". Output: " .. result.stderr, vim.log.levels.ERROR)
--   end
-- end)

-- local mcphub = require "mcphub"
--
-- mcphub.setup {
-- }
